name: Pixlet

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libwebp-dev

      - name: Run buildifier
        run: go tool buildifier -d -r ./

      - name: Lint Go
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m

  build-and-test-release:
    name: Build and Test (${{ matrix.release_arch }})
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            release_arch: linux-amd64
          - os: ubuntu-24.04-arm
            release_arch: linux-arm64
          - os: macos-15-intel
            release_arch: darwin-amd64
            library_path: "/usr/local/lib"
            cgo_cppflags: "-I/usr/local/include"
          - os: macos-latest
            release_arch: darwin-arm64
            library_path: "/opt/homebrew/lib"
            cgo_cppflags: "-I/opt/homebrew/include"
          - os: windows-latest
            release_arch: windows-amd64

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: "lts/Krypton"

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: mingw64
          update: true
          install: >-
            make
            curl
            mingw-w64-x86_64-toolchain
          path-type: inherit

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libwebp-dev

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install webp

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          set MSYSTEM=MINGW64
          curl -LO https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-libwebp-1.6.0-1-any.pkg.tar.zst
          pacman -U --noconfirm mingw-w64-x86_64-libwebp-1.6.0-1-any.pkg.tar.zst

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Check for stale generated files
        if: matrix.os == 'ubuntu-24.04'
        run: |
          go generate -x ./...
          git diff --exit-code -- .  ':!frontend/package-lock.json'

      - name: Update package.json version
        if: github.ref_type == 'tag'
        shell: bash
        working-directory: frontend
        env:
          tag: ${{ github.ref_name }}
        run: |
          VERSION=${tag#v}
          npm version $VERSION --no-git-tag-version --allow-same-version

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build
        run: go build -tags="timetzdata,gzip_fonts,netgo,osusergo" github.com/tronbyt/pixlet
        env:
          LIBRARY_PATH: ${{ matrix.library_path }}
          CGO_CPPFLAGS: ${{ matrix.cgo_cppflags }}

      - name: Test
        run: go test -tags="timetzdata,gzip_fonts,netgo,osusergo" -v -cover ./...
        env:
          LIBRARY_PATH: ${{ matrix.library_path }}
          CGO_CPPFLAGS: ${{ matrix.cgo_cppflags }}

      - name: Build Release
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p build
          LDFLAGS="-w -s -X 'github.com/tronbyt/pixlet/runtime.Version=${{ github.ref_name }}'"
          if [ "${{ runner.os }}" != "macOS" ]; then
             LDFLAGS="$LDFLAGS '-extldflags=-static -lsharpyuv'"
          fi

          CGO_ENABLED=1 go build \
            -ldflags="$LDFLAGS" \
            -tags="timetzdata,gzip_fonts,netgo,osusergo" \
            -trimpath \
            -o build/ \
            github.com/tronbyt/pixlet

          BINARY="pixlet"
          if [ "${{ runner.os }}" == "Windows" ]; then
            BINARY="pixlet.exe"
          fi

          tar -cvz -C build -f "build/pixlet_${{ github.ref_name }}_${{ matrix.release_arch }}.tar.gz" "$BINARY"
        env:
          LIBRARY_PATH: ${{ matrix.library_path }}
          CGO_CPPFLAGS: ${{ matrix.cgo_cppflags }}

      - name: Upload Release Artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts-${{ matrix.os }}
          path: build

  update-package-json:
    name: Update package.json version
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "lts/Krypton"

      - name: Update package.json version
        working-directory: frontend
        env:
          tag: ${{ github.ref_name }}
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${tag#v}
          echo "Updating package.json version to $VERSION"

          # Update package.json version
          npm install
          npm version $VERSION --no-git-tag-version --allow-same-version
          npm run build

          # Commit and push the change
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "Update package.json version to $VERSION" || exit 0
          git push origin HEAD:main

  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    needs: [build-and-test-release]
    if: github.ref_type == 'tag'
    permissions:
      contents: write

    steps:
      - name: Fetch Release Artifacts
        uses: actions/download-artifact@v8
        with:
          path: build
          pattern: release-artifacts-*
          merge-multiple: true

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              build/*.tar.gz

  build-and-push-image:
    name: Build Image
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PIXLET_VERSION=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
